<?php

namespace Database\Seeders;

use App\Models\Farmaco;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class FarmacosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $farmacos = [
            /* ['descripcion' =>	'AC. ACETIL-SALICILICO',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'100 mg',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'AC. ACETIL-SALICILICO',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'500 mg',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'AC. TRANEXÁMICO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'1000 mg/10 mL',	'stock_maximo' =>	 6 	,'controlado' =>	 null 	],
            ['descripcion' =>	'ADIFENINA/PROPIFENAZONA',	'forma_farmaceutica' =>	'Supositorio',	'dosis' =>	'50/440 mg',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'ADIFENINA/PROPIFENAZONA',	'forma_farmaceutica' =>	'Supositorio',	'dosis' =>	'25/220 mg',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'AMINOFILINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'250 mg/5ml',	'stock_maximo' =>	 5 	,'controlado' =>	 null 	],
            ['descripcion' =>	'AMOXICILINA',	'forma_farmaceutica' =>	'Cápsula',	'dosis' =>	'500 mg',	'stock_maximo' =>	 100 	,'controlado' =>	 null 	],
            ['descripcion' =>	'AMOXICILINA',	'forma_farmaceutica' =>	'Polvo para suspensión oral',	'dosis' =>	'500 mg/5 mL',	'stock_maximo' =>	 15 	,'controlado' =>	 null 	],
            ['descripcion' =>	'AMOXICILINA + ACIDO CLAVULANICO',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'500-875 mg + 125 mg',	'stock_maximo' =>	 100 	,'controlado' =>	 null 	],
            ['descripcion' =>	'ATORVASTATINA',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'40 mg',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'AZITROMICINA ',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'500 mg',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'BENCILPENICILINA',	'forma_farmaceutica' =>	'Polvo para solución inyectable',	'dosis' =>	'2.000.000 UI',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'BENCILPENICILINA',	'forma_farmaceutica' =>	'Polvo para solución inyectable',	'dosis' =>	'1.000.000 UI',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'BENCILPENICILINA BENZATINA ',	'forma_farmaceutica' =>	'Polvo para solución inyectable',	'dosis' =>	'1.200.000 UI',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'BETAMETASONA (FOSFATO DISODICO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'4 mg/1 mL',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'BUDESONIDA',	'forma_farmaceutica' =>	'Aerosol para inhalación',	'dosis' =>	'200 mcg/dosis',	'stock_maximo' =>	 5 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CALCIO GLUCONATO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,1',	'stock_maximo' =>	 4 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CAPTOPRIL',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'25-50 mg',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CEFADROXILO ',	'forma_farmaceutica' =>	'Polvo para suspensión oral',	'dosis' =>	'250 mg/5 mL',	'stock_maximo' =>	 8 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CEFADROXILO ',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'500 mg',	'stock_maximo' =>	 40 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CEFAZOLINA ',	'forma_farmaceutica' =>	'Polvo para solución inyectable',	'dosis' =>	'1000 g',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CEFTRIAXONA',	'forma_farmaceutica' =>	'Polvo para solución inyectable',	'dosis' =>	'1000 g',	'stock_maximo' =>	 40 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLARITROMICINA',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'500 mg',	'stock_maximo' =>	 40 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLARITROMICINA',	'forma_farmaceutica' =>	'Polvo para suspensión oral',	'dosis' =>	'250 mg/5 mL',	'stock_maximo' =>	 5 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLONIXINATO DE LISINA ',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'100 mg/2 mL',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLONIXINATO DE LISINA ',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'125 mg',	'stock_maximo' =>	 50 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLOPIDROGEL',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'75 mg',	'stock_maximo' =>	 4 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLOPIDROGEL',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'300 mg',	'stock_maximo' =>	 8 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLORAMFENICOL',	'forma_farmaceutica' =>	'Solución oftálmica',	'dosis' =>	'0,005',	'stock_maximo' =>	 5 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLORAMFENICOL',	'forma_farmaceutica' =>	'Ungüento oftálmico',	'dosis' =>	'0,01',	'stock_maximo' =>	 5 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLORFENAMINA',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'4 mg',	'stock_maximo' =>	 40 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLORFENAMINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 12 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLORPROMAZINA (Clorhidrato)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'12,5 mg/mL',	'stock_maximo' =>	 8 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLORPROMAZINA (Clorhidrato)',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'100mg',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLOXACILINA (Sódica)',	'forma_farmaceutica' =>	'Polvo para solución inyectable',	'dosis' =>	'500 mg',	'stock_maximo' =>	 15 	,'controlado' =>	 null 	],
            ['descripcion' =>	'CLOXACILINA (Sódica)',	'forma_farmaceutica' =>	'Cápsula o comprimido',	'dosis' =>	'500 mg',	'stock_maximo' =>	 80 	,'controlado' =>	 null 	],
            ['descripcion' =>	'COTRIMOXAZOL',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'SMT 800+ TMP 160 mg',	'stock_maximo' =>	 50 	,'controlado' =>	 null 	],
            ['descripcion' =>	'COTRIMOXAZOL',	'forma_farmaceutica' =>	'Suspensión oral',	'dosis' =>	'SMT 200 mg + TMP 40 mg/5ml',	'stock_maximo' =>	 8 	,'controlado' =>	 null 	],
            ['descripcion' =>	'DEXAMETASONA (FOSFATO DISODICO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'4 mg/ml',	'stock_maximo' =>	 12 	,'controlado' =>	 null 	],
            ['descripcion' =>	'DIAZEPAM',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/2 mL',	'stock_maximo' =>	 15 	,'controlado' =>	 1 	],
            ['descripcion' =>	'DICLOFENACO (Sódico)',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'50 mg',	'stock_maximo' =>	 100 	,'controlado' =>	 null 	],
            ['descripcion' =>	'DICLOFENACO (Sódico)',	'forma_farmaceutica' =>	'Supositorio infantil',	'dosis' =>	'12,5 mg',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'DICLOFENACO (Sódico)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'75 mg/3 mL',	'stock_maximo' =>	 30 	,'controlado' =>	 null 	],
            ['descripcion' =>	'DOMPERIDONA (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'5 mg/ml',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'DOMPERIDONA (CLOHIDRATO)',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'10 mg',	'stock_maximo' =>	 40 	,'controlado' =>	 null 	],
            ['descripcion' =>	'DOMPERIDONA (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución para gotas',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 5 	,'controlado' =>	 null 	],
            ['descripcion' =>	'ENOXAPARINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'40 mg',	'stock_maximo' =>	 12 	,'controlado' =>	 null 	],
            ['descripcion' =>	'ENOXAPARINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'60 mg',	'stock_maximo' =>	 12 	,'controlado' =>	 null 	],
            ['descripcion' =>	'FENITOINA (Sódica)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'FENTANILO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,5 mg/1 mL',	'stock_maximo' =>	 10 	,'controlado' =>	 1 	],
            ['descripcion' =>	'FITOMENADIONA',	'forma_farmaceutica' =>	'Solución inyectable (IM)',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 8 	,'controlado' =>	 null 	],
            ['descripcion' =>	'FITOMENADIONA ',	'forma_farmaceutica' =>	'Solución inyectable (EV)',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 8 	,'controlado' =>	 null 	],
            ['descripcion' =>	'ENEMA FOSFATO',	'forma_farmaceutica' =>	'Solución laxante rectal',	'dosis' =>	'según formula',	'stock_maximo' =>	 8 	,'controlado' =>	 null 	],
            ['descripcion' =>	'FLUCLOXACILINA',	'forma_farmaceutica' =>	'Polvo para suspensión oral',	'dosis' =>	'250 mg/ 5 mL',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'FLUCLOXACILINA',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'500mg',	'stock_maximo' =>	 60 	,'controlado' =>	 null 	],
            ['descripcion' =>	'FUROSEMIDA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'20 mg/mL',	'stock_maximo' =>	 14 	,'controlado' =>	 null 	],
            ['descripcion' =>	'GENTAMICINA (Sulfato)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'40 -80 mg/ml',	'stock_maximo' =>	 18 	,'controlado' =>	 null 	],
            ['descripcion' =>	'GENTAMICINA Sulfato',	'forma_farmaceutica' =>	'Solución oftálmica',	'dosis' =>	'0,003',	'stock_maximo' =>	 5 	,'controlado' =>	 null 	],
            ['descripcion' =>	'GENTAMICINA Sulfato',	'forma_farmaceutica' =>	'Ungüento oftálmico',	'dosis' =>	'0,003',	'stock_maximo' =>	 5 	,'controlado' =>	 null 	],
            ['descripcion' =>	'GLUCAGON',	'forma_farmaceutica' =>	'Polvo para solución Inyectable',	'dosis' =>	'1 mg',	'stock_maximo' =>	 4 	,'controlado' =>	 null 	],
            ['descripcion' =>	'GLUCOSA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,3',	'stock_maximo' =>	 8 	,'controlado' =>	 null 	],
            ['descripcion' =>	'HALOPERIDOL  (Decanoato)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'5 mg/mL',	'stock_maximo' =>	 6 	,'controlado' =>	 null 	],
            ['descripcion' =>	'HIDROCORTISONA  (Succinato)',	'forma_farmaceutica' =>	'Polvo  para solución inyectable',	'dosis' =>	'100 mg',	'stock_maximo' =>	 6 	,'controlado' =>	 null 	],
            ['descripcion' =>	'HIDROCORTISONA  (Succinato)',	'forma_farmaceutica' =>	'Polvo  para solución inyectable',	'dosis' =>	'500mg',	'stock_maximo' =>	 12 	,'controlado' =>	 null 	],
            ['descripcion' =>	'IBUPROFENO',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'400 mg',	'stock_maximo' =>	 150 	,'controlado' =>	 null 	],
            ['descripcion' =>	'IBUPROFENO',	'forma_farmaceutica' =>	'Suspensión oral',	'dosis' =>	'100 mg/5 mL',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'IBUPROFENO',	'forma_farmaceutica' =>	'Suspensión oral',	'dosis' =>	'200 mg/5 mL',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'INSULINA HUMANA CRISTALINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'100 UI/mL',	'stock_maximo' =>	 1 	,'controlado' =>	 null 	],
            ['descripcion' =>	'IPRATROPIO Bromuro/FENOTEROL',	'forma_farmaceutica' =>	'Solución para nebulización',	'dosis' =>	'20/5 mcg/dosis',	'stock_maximo' =>	 2 	,'controlado' =>	 null 	],
            ['descripcion' =>	'IPRATROPIO BROMURO',	'forma_farmaceutica' =>	'Aerosol para inhalación',	'dosis' =>	'20 mcg/dosis',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'KETOROLACO',	'forma_farmaceutica' =>	'Solución Inyectable',	'dosis' =>	'30 mg/ml',	'stock_maximo' =>	 50 	,'controlado' =>	 null 	],
            ['descripcion' =>	'LABETALOL (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'5 mg/ml',	'stock_maximo' =>	 5 	,'controlado' =>	 null 	],
            ['descripcion' =>	'LEVONORGESTREL',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'0,75 - 1,5 mg',	'stock_maximo' =>	 6 	,'controlado' =>	 null 	],
            ['descripcion' =>	'LIDOCAINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,02',	'stock_maximo' =>	 5 	,'controlado' =>	 null 	],
            ['descripcion' =>	'LORAZEPAM',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'4 mg/2 mL',	'stock_maximo' =>	 10 	,'controlado' =>	 1 	],
            ['descripcion' =>	'LORATADINA',	'forma_farmaceutica' =>	'Solución oral',	'dosis' =>	'5 mg/5 mL',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'METAMIZOL SODICO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,5 g/ml',	'stock_maximo' =>	 50 	,'controlado' =>	 null 	],
            ['descripcion' =>	'METAMIZOL SODICO',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'300 mg',	'stock_maximo' =>	 200 	,'controlado' =>	 null 	],
            ['descripcion' =>	'METAMIZOL SODICO',	'forma_farmaceutica' =>	'Supositorio',	'dosis' =>	'250 mg',	'stock_maximo' =>	 15 	,'controlado' =>	 null 	],
            ['descripcion' =>	'METOCLOPRAMIDA (Clorhidrato)',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'10 mg',	'stock_maximo' =>	 60 	,'controlado' =>	 null 	],
            ['descripcion' =>	'METOCLOPRAMIDA (Clorhidrato)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'5 mg/ml',	'stock_maximo' =>	 30 	,'controlado' =>	 null 	],
            ['descripcion' =>	'MIDAZOLAM',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'15 mg/3 ml',	'stock_maximo' =>	 7 	,'controlado' =>	 1 	],
            ['descripcion' =>	'MORFINA (Clorhidrato) ',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 8 	,'controlado' =>	 1 	],
            ['descripcion' =>	'N-ACETILCISTEINA',	'forma_farmaceutica' =>	'Solución para nebulización',	'dosis' =>	'100mg/ml',	'stock_maximo' =>	 2 	,'controlado' =>	 null 	],
            ['descripcion' =>	'NITROFURANTOINA',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'100 mg',	'stock_maximo' =>	 40 	,'controlado' =>	 null 	],
            ['descripcion' =>	'OMEPRAZOL',	'forma_farmaceutica' =>	'Frasco ampolla + solvente',	'dosis' =>	'40mg',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'ONDANSETRON ',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'4 mg/2 mL',	'stock_maximo' =>	 12 	,'controlado' =>	 null 	],
            ['descripcion' =>	'OSELTAMIVIR',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'75mg',	'stock_maximo' =>	 30 	,'controlado' =>	 null 	],
            ['descripcion' =>	'OSELTAMIVIR',	'forma_farmaceutica' =>	'Suspensión oral',	'dosis' =>	'12mg/ml',	'stock_maximo' =>	 3 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PAPAVERINA  (HCL)+ ATROPINA',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'40 mg/0.5 mg',	'stock_maximo' =>	 60 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PAPAVERINA (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'40 mg/ml',	'stock_maximo' =>	 8 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PARACETAMOL',	'forma_farmaceutica' =>	'Solución oral para gotas',	'dosis' =>	'100 mg/mL',	'stock_maximo' =>	 30 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PARACETAMOL',	'forma_farmaceutica' =>	'Supositorio',	'dosis' =>	'125 mg',	'stock_maximo' =>	 30 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PARACETAMOL',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'500 mg',	'stock_maximo' =>	 300 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PARACETAMOL',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'1000 mg/100 mL',	'stock_maximo' =>	 6 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PARGEVERINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'5 mg/ml',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PARGEVERINA',	'forma_farmaceutica' =>	'Solución para gotas orales',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'POTASIO CLORURO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,1',	'stock_maximo' =>	 6 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PREDNISONA',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'5 mg',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PREDNISONA',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'20 mg',	'stock_maximo' =>	 60 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PREDNISONA',	'forma_farmaceutica' =>	'Suspensión oral',	'dosis' =>	'20 mg/5 ml',	'stock_maximo' =>	 25 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PROGESTERONA',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'200 mg ',	'stock_maximo' =>	 30 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PROPANOLOL',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'10 mg',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PROPANOLOL',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'40 mg',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PROPANOLOL (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'1 mg/ml',	'stock_maximo' =>	 4 	,'controlado' =>	 null 	],
            ['descripcion' =>	'PROPARACAINA CLORHIDRATO',	'forma_farmaceutica' =>	'Solución oftálmica',	'dosis' =>	'0,5%',	'stock_maximo' =>	 1 	,'controlado' =>	 null 	],
            ['descripcion' =>	'RANITIDINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 10 	,'controlado' =>	 null 	],
            ['descripcion' =>	'RANITIDINA',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'300 mg',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'SALBUTAMOL (Sulfato)',	'forma_farmaceutica' =>	'Solución para nebulización',	'dosis' =>	'5 mg/ml',	'stock_maximo' =>	 3 	,'controlado' =>	 null 	],
            ['descripcion' =>	'SALBUTAMOL (Sulfato)',	'forma_farmaceutica' =>	'Suspensión para inhalación',	'dosis' =>	'100 mcg/dosis',	'stock_maximo' =>	 30 	,'controlado' =>	 null 	],
            ['descripcion' =>	'SALES  REHIDRATANTES',	'forma_farmaceutica' =>	'Solución oral',	'dosis' =>	'60 mEq de sodio/litro',	'stock_maximo' =>	 15 	,'controlado' =>	 null 	],
            ['descripcion' =>	'SALES  REHIDRATANTES',	'forma_farmaceutica' =>	'Solución oral',	'dosis' =>	'90 mEq de sodio/litro',	'stock_maximo' =>	 15 	,'controlado' =>	 null 	],
            ['descripcion' =>	'SODIO BICARBONATO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'8,4%',	'stock_maximo' =>	 8 	,'controlado' =>	 null 	],
            ['descripcion' =>	'TIAMINA ',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'30 mg/mL',	'stock_maximo' =>	 30 	,'controlado' =>	 null 	],
            ['descripcion' =>	'AEROCAMARA',	'forma_farmaceutica' =>	'Unidad',	'dosis' =>	'Pediátrica',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	],
            ['descripcion' =>	'AEROCAMARA',	'forma_farmaceutica' =>	'Unidad',	'dosis' =>	'Adulto',	'stock_maximo' =>	 20 	,'controlado' =>	 null 	], */

            //carro de urgencias
['descripcion' =>	'AC. ACETIL-SALICILICO',	'forma_farmaceutica' =>	'Comprimido',	'dosis' =>	'500 mg',	'stock_maximo' =>	 10 	,	'controlado' =>	null],
['descripcion' =>	'ADENOSINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'6 mg/2ml',	'stock_maximo' =>	 6 	,	'controlado' =>	null],
['descripcion' =>	'AGUA DESTILADA',	'forma_farmaceutica' =>	'Ampollas',	'dosis' =>	'5 ml ó 10 ml',	'stock_maximo' =>	 5 	,	'controlado' =>	null],
['descripcion' =>	'AMIODARONA (clorhidrato)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'150 mg/3ml',	'stock_maximo' =>	 10 	,	'controlado' =>	null],
['descripcion' =>	'ATROPINA Sulfato',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'1 mg/mL',	'stock_maximo' =>	 10 	,	'controlado' =>	null],
['descripcion' =>	'BETAMETASONA (FOSFATO DISODICO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'4 mg/1 mL',	'stock_maximo' =>	 3 	,	'controlado' =>	null],
['descripcion' =>	'CALCIO GLUCONATO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,1',	'stock_maximo' =>	 3 	,	'controlado' =>	null],
['descripcion' =>	'CLOPIDROGEL',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'75 mg',	'stock_maximo' =>	 6 	,	'controlado' =>	null],
['descripcion' =>	'CLOPIDROGEL',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'300 mg',	'stock_maximo' =>	 6 	,	'controlado' =>	null],
['descripcion' =>	'CLORFENAMINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 3 	,	'controlado' =>	null],
['descripcion' =>	'DEXAMETASONA (FOSFATO DISODICO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'4 mg/ml',	'stock_maximo' =>	 3 	,	'controlado' =>	null],
['descripcion' =>	'DIAZEPAM ',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/2 mL',	'stock_maximo' =>	 5 	,	'controlado' =>	1],
['descripcion' =>	'DOPAMINA (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'40 mg/ml',	'stock_maximo' =>	 3 	,	'controlado' =>	null],
['descripcion' =>	'EPINEFRINA (Clorhidrato)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'1 mg/mL',	'stock_maximo' =>	 10 	,	'controlado' =>	null],
['descripcion' =>	'ETOMIDATO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'20 mg/10 mL',	'stock_maximo' =>	 5 	,	'controlado' =>	null],
['descripcion' =>	'FENITOINA (Sódica)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 6 	,	'controlado' =>	null],
['descripcion' =>	'FENTANILO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,5 mg/1 mL',	'stock_maximo' =>	 4 	,	'controlado' =>	1],
['descripcion' =>	'FLUMAZENILO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,1 mg/ mL',	'stock_maximo' =>	 5 	,	'controlado' =>	null],
['descripcion' =>	'FUROSEMIDA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'20 mg/mL',	'stock_maximo' =>	 6 	,	'controlado' =>	null],
['descripcion' =>	'GLUCOSA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,3',	'stock_maximo' =>	 4 	,	'controlado' =>	null],
['descripcion' =>	'HIDROCORTISONA  (Succinato)',	'forma_farmaceutica' =>	'Polvo  para solución inyectable',	'dosis' =>	'100 mg',	'stock_maximo' =>	 5 	,	'controlado' =>	null],
['descripcion' =>	'HIDROCORTISONA  (Succinato)',	'forma_farmaceutica' =>	'Polvo  para solución inyectable',	'dosis' =>	'500mg',	'stock_maximo' =>	 5 	,	'controlado' =>	null],
['descripcion' =>	'KETAMINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'500 mg/10 mL',	'stock_maximo' =>	 2 	,	'controlado' =>	1],
['descripcion' =>	'LABETALOL (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'5mg/ml',	'stock_maximo' =>	 1 	,	'controlado' =>	null],
['descripcion' =>	'LANATOSIDO C',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0.2 mg/ml',	'stock_maximo' =>	 4 	,	'controlado' =>	null],
['descripcion' =>	'LIDOCAINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,02',	'stock_maximo' =>	 5 	,	'controlado' =>	null],
['descripcion' =>	'LORAZEPAM  ',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'4 mg/ 2 mL',	'stock_maximo' =>	 10 	,	'controlado' =>	1],
['descripcion' =>	'MAGNESIO (SULFATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,25',	'stock_maximo' =>	 3 	,	'controlado' =>	null],
['descripcion' =>	'MIDAZOLAM',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'15 mg/3 ml',	'stock_maximo' =>	 3 	,	'controlado' =>	1],
['descripcion' =>	'MORFINA (Clorhidrato)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 3 	,	'controlado' =>	1],
['descripcion' =>	'N-ACETILCISTEINA',	'forma_farmaceutica' =>	'Solución para nebulización',	'dosis' =>	'100mg/ml',	'stock_maximo' =>	 1 	,	'controlado' =>	null],
['descripcion' =>	'NALOXONA (CLORHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,4 mg/mL',	'stock_maximo' =>	 5 	,	'controlado' =>	null],
['descripcion' =>	'NITROGLICERINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'5 mg/ml',	'stock_maximo' =>	 2 	,	'controlado' =>	null],
['descripcion' =>	'NOREPINEFRINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'1mg/ml',	'stock_maximo' =>	 4 	,	'controlado' =>	null],
['descripcion' =>	'OXITOCINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'5 U.I /mL',	'stock_maximo' =>	 8 	,	'controlado' =>	null],
['descripcion' =>	'PETIDINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'100 mg/2 mL',	'stock_maximo' =>	 4 	,	'controlado' =>	1],
['descripcion' =>	'PROPANOLOL',	'forma_farmaceutica' =>	'Comprimidos',	'dosis' =>	'40 mg',	'stock_maximo' =>	 10 	,	'controlado' =>	null],
['descripcion' =>	'PROPANOLOL (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'1mg/ml',	'stock_maximo' =>	 4 	,	'controlado' =>	null],
['descripcion' =>	'SALBUTAMOL ( Sulfato)',	'forma_farmaceutica' =>	'Solución para nebulización',	'dosis' =>	'5 mg/ml',	'stock_maximo' =>	 2 	,	'controlado' =>	null],
['descripcion' =>	'SODIO CLORURO',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,009',	'stock_maximo' =>	 10 	,	'controlado' =>	null],
['descripcion' =>	'SUCCINILCOLINA',	'forma_farmaceutica' =>	'Polvo para solución inyectable',	'dosis' =>	'100 mg',	'stock_maximo' =>	 3 	,	'controlado' =>	null],
['descripcion' =>	'TENECTEPLASA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10.000 UI',	'stock_maximo' =>	 1 	,	'controlado' =>	null],
['descripcion' =>	'VECURONIO Bromuro de',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/2,5ml',	'stock_maximo' =>	 2 	,	'controlado' =>	null],
['descripcion' =>	'VERAPAMILO (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'2.5 mg/ml',	'stock_maximo' =>	 3 	,	'controlado' =>	null],

//maletin urgencias

['descripcion' =>	'ADENOSINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'6 mg/2ml',	'stock_maximo' =>	 3 	,	'controlado' =>	null],
['descripcion' =>	'AGUA DESTILADA',	'forma_farmaceutica' =>	'Ampollas',	'dosis' =>	'10 ml',	'stock_maximo' =>	 3 	,	'controlado' =>	null],
['descripcion' =>	'AMIODARONA (clorhidrato)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'150 mg/3ml',	'stock_maximo' =>	 4 	,	'controlado' =>	null],
['descripcion' =>	'CLORFENAMINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/ml',	'stock_maximo' =>	 2 	,	'controlado' =>	null],
['descripcion' =>	'CLORPROMAZINA (Clorhidrato)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'12,5 mg/ mL',	'stock_maximo' =>	 2 	,	'controlado' =>	null],
['descripcion' =>	'DEXAMETASONA (FOSFATO DISODICO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'4 mg/ml',	'stock_maximo' =>	 2 	,	'controlado' =>	null],
['descripcion' =>	'DIAZEPAM ',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'10 mg/  2mL',	'stock_maximo' =>	 1 	,	'controlado' =>	null],
['descripcion' =>	'DOPAMINA (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'40 mg/ml',	'stock_maximo' =>	 1 	,	'controlado' =>	null],
['descripcion' =>	'EPINEFRINA (Clorhidrato)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'1 mg/mL',	'stock_maximo' =>	 2 	,	'controlado' =>	null],
['descripcion' =>	'FUROSEMIDA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'20 mg/mL',	'stock_maximo' =>	 4 	,	'controlado' =>	null],
['descripcion' =>	'GLUCOSA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,3',	'stock_maximo' =>	 5 	,	'controlado' =>	null],
['descripcion' =>	'HIDROCORTISONA  (Succinato)',	'forma_farmaceutica' =>	'Polvo para solución inyectable',	'dosis' =>	'500mg',	'stock_maximo' =>	 2 	,	'controlado' =>	null],
['descripcion' =>	'KETAMINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'500 mg/10 mL',	'stock_maximo' =>	 4 	,	'controlado' =>	null],
['descripcion' =>	'LANATOSIDO C',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0.2 mg/ml',	'stock_maximo' =>	 2 	,	'controlado' =>	null],
['descripcion' =>	'LIDOCAINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'0,02',	'stock_maximo' =>	 2 	,	'controlado' =>	null],
['descripcion' =>	'MIDAZOLAM',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'15 mg/3 ml',	'stock_maximo' =>	 4 	,	'controlado' =>	null],
['descripcion' =>	'NOREPINEFRINA',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'1mg/ml',	'stock_maximo' =>	 3 	,	'controlado' =>	null],
['descripcion' =>	'VERAPAMILO (CLOHIDRATO)',	'forma_farmaceutica' =>	'Solución inyectable',	'dosis' =>	'2.5 mg/ml',	'stock_maximo' =>	 2 	,	'controlado' =>	null],

        ];
        foreach ($farmacos as $farmaco) {
            Farmaco::updateOrCreate($farmaco);
        }
    }
}
