<?php

namespace Database\Seeders;

use App\Models\AreaFarmaco;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class FarmacoAreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $farmacos = [
            //botiquin urgencias
            array('area_id' =>1, 'farmaco_id' =>	1	),
            array('area_id' =>1, 'farmaco_id' =>	2	),
            array('area_id' =>1, 'farmaco_id' =>	3	),
            array('area_id' =>1, 'farmaco_id' =>	4	),
            array('area_id' =>1, 'farmaco_id' =>	5	),
            array('area_id' =>1, 'farmaco_id' =>	6	),
            array('area_id' =>1, 'farmaco_id' =>	7	),
            array('area_id' =>1, 'farmaco_id' =>	8	),
            array('area_id' =>1, 'farmaco_id' =>	9	),
            array('area_id' =>1, 'farmaco_id' =>	10	),
            array('area_id' =>1, 'farmaco_id' =>	11	),
            array('area_id' =>1, 'farmaco_id' =>	12	),
            array('area_id' =>1, 'farmaco_id' =>	13	),
            array('area_id' =>1, 'farmaco_id' =>	14	),
            array('area_id' =>1, 'farmaco_id' =>	15	),
            array('area_id' =>1, 'farmaco_id' =>	16	),
            array('area_id' =>1, 'farmaco_id' =>	17	),
            array('area_id' =>1, 'farmaco_id' =>	18	),
            array('area_id' =>1, 'farmaco_id' =>	19	),
            array('area_id' =>1, 'farmaco_id' =>	20	),
            array('area_id' =>1, 'farmaco_id' =>	21	),
            array('area_id' =>1, 'farmaco_id' =>	22	),
            array('area_id' =>1, 'farmaco_id' =>	23	),
            array('area_id' =>1, 'farmaco_id' =>	24	),
            array('area_id' =>1, 'farmaco_id' =>	25	),
            array('area_id' =>1, 'farmaco_id' =>	26	),
            array('area_id' =>1, 'farmaco_id' =>	27	),
            array('area_id' =>1, 'farmaco_id' =>	28	),
            array('area_id' =>1, 'farmaco_id' =>	29	),
            array('area_id' =>1, 'farmaco_id' =>	30	),
            array('area_id' =>1, 'farmaco_id' =>	31	),
            array('area_id' =>1, 'farmaco_id' =>	32	),
            array('area_id' =>1, 'farmaco_id' =>	33	),
            array('area_id' =>1, 'farmaco_id' =>	34	),
            array('area_id' =>1, 'farmaco_id' =>	35	),
            array('area_id' =>1, 'farmaco_id' =>	36	),
            array('area_id' =>1, 'farmaco_id' =>	37	),
            array('area_id' =>1, 'farmaco_id' =>	38	),
            array('area_id' =>1, 'farmaco_id' =>	39	),
            array('area_id' =>1, 'farmaco_id' =>	40	),
            array('area_id' =>1, 'farmaco_id' =>	41	),
            array('area_id' =>1, 'farmaco_id' =>	42	),
            array('area_id' =>1, 'farmaco_id' =>	43	),
            array('area_id' =>1, 'farmaco_id' =>	44	),
            array('area_id' =>1, 'farmaco_id' =>	45	),
            array('area_id' =>1, 'farmaco_id' =>	46	),
            array('area_id' =>1, 'farmaco_id' =>	47	),
            array('area_id' =>1, 'farmaco_id' =>	48	),
            array('area_id' =>1, 'farmaco_id' =>	49	),
            array('area_id' =>1, 'farmaco_id' =>	50	),
            array('area_id' =>1, 'farmaco_id' =>	51	),
            array('area_id' =>1, 'farmaco_id' =>	52	),
            array('area_id' =>1, 'farmaco_id' =>	53	),
            array('area_id' =>1, 'farmaco_id' =>	54	),
            array('area_id' =>1, 'farmaco_id' =>	55	),
            array('area_id' =>1, 'farmaco_id' =>	56	),
            array('area_id' =>1, 'farmaco_id' =>	57	),
            array('area_id' =>1, 'farmaco_id' =>	58	),
            array('area_id' =>1, 'farmaco_id' =>	59	),
            array('area_id' =>1, 'farmaco_id' =>	60	),
            array('area_id' =>1, 'farmaco_id' =>	61	),
            array('area_id' =>1, 'farmaco_id' =>	62	),
            array('area_id' =>1, 'farmaco_id' =>	63	),
            array('area_id' =>1, 'farmaco_id' =>	64	),
            array('area_id' =>1, 'farmaco_id' =>	65	),
            array('area_id' =>1, 'farmaco_id' =>	66	),
            array('area_id' =>1, 'farmaco_id' =>	67	),
            array('area_id' =>1, 'farmaco_id' =>	68	),
            array('area_id' =>1, 'farmaco_id' =>	69	),
            array('area_id' =>1, 'farmaco_id' =>	70	),
            array('area_id' =>1, 'farmaco_id' =>	71	),
            array('area_id' =>1, 'farmaco_id' =>	72	),
            array('area_id' =>1, 'farmaco_id' =>	73	),
            array('area_id' =>1, 'farmaco_id' =>	74	),
            array('area_id' =>1, 'farmaco_id' =>	75	),
            array('area_id' =>1, 'farmaco_id' =>	76	),
            array('area_id' =>1, 'farmaco_id' =>	77	),
            array('area_id' =>1, 'farmaco_id' =>	78	),
            array('area_id' =>1, 'farmaco_id' =>	79	),
            array('area_id' =>1, 'farmaco_id' =>	80	),
            array('area_id' =>1, 'farmaco_id' =>	81	),
            array('area_id' =>1, 'farmaco_id' =>	82	),
            array('area_id' =>1, 'farmaco_id' =>	83	),
            array('area_id' =>1, 'farmaco_id' =>	84	),
            array('area_id' =>1, 'farmaco_id' =>	85	),
            array('area_id' =>1, 'farmaco_id' =>	86	),
            array('area_id' =>1, 'farmaco_id' =>	87	),
            array('area_id' =>1, 'farmaco_id' =>	88	),
            array('area_id' =>1, 'farmaco_id' =>	89	),
            array('area_id' =>1, 'farmaco_id' =>	90	),
            array('area_id' =>1, 'farmaco_id' =>	91	),
            array('area_id' =>1, 'farmaco_id' =>	92	),
            array('area_id' =>1, 'farmaco_id' =>	93	),
            array('area_id' =>1, 'farmaco_id' =>	94	),
            array('area_id' =>1, 'farmaco_id' =>	95	),
            array('area_id' =>1, 'farmaco_id' =>	96	),
            array('area_id' =>1, 'farmaco_id' =>	97	),
            array('area_id' =>1, 'farmaco_id' =>	98	),
            array('area_id' =>1, 'farmaco_id' =>	99	),
            array('area_id' =>1, 'farmaco_id' =>	100	),
            array('area_id' =>1, 'farmaco_id' =>	101	),
            array('area_id' =>1, 'farmaco_id' =>	102	),
            array('area_id' =>1, 'farmaco_id' =>	103	),
            array('area_id' =>1, 'farmaco_id' =>	104	),
            array('area_id' =>1, 'farmaco_id' =>	105	),
            array('area_id' =>1, 'farmaco_id' =>	106	),
            array('area_id' =>1, 'farmaco_id' =>	107	),
            array('area_id' =>1, 'farmaco_id' =>	108	),
            array('area_id' =>1, 'farmaco_id' =>	109	),
            array('area_id' =>1, 'farmaco_id' =>	110	),
            array('area_id' =>1, 'farmaco_id' =>	111	),
            array('area_id' =>1, 'farmaco_id' =>	112	),
            array('area_id' =>1, 'farmaco_id' =>	113	),
            array('area_id' =>1, 'farmaco_id' =>	114	),
            array('area_id' =>1, 'farmaco_id' =>	115	),
            array('area_id' =>1, 'farmaco_id' =>	116	),
            array('area_id' =>2, 'farmaco_id' =>	117	),
            array('area_id' =>2, 'farmaco_id' =>	118	),
            array('area_id' =>2, 'farmaco_id' =>	119	),
            array('area_id' =>2, 'farmaco_id' =>	120	),
            array('area_id' =>2, 'farmaco_id' =>	121	),
            array('area_id' =>2, 'farmaco_id' =>	122	),
            array('area_id' =>2, 'farmaco_id' =>	123	),
            array('area_id' =>2, 'farmaco_id' =>	124	),
            array('area_id' =>2, 'farmaco_id' =>	125	),
            array('area_id' =>2, 'farmaco_id' =>	126	),
            array('area_id' =>2, 'farmaco_id' =>	127	),
            array('area_id' =>2, 'farmaco_id' =>	128	),
            array('area_id' =>2, 'farmaco_id' =>	129	),
            array('area_id' =>2, 'farmaco_id' =>	130	),
            array('area_id' =>2, 'farmaco_id' =>	131	),
            array('area_id' =>2, 'farmaco_id' =>	132	),
            array('area_id' =>2, 'farmaco_id' =>	133	),
            array('area_id' =>2, 'farmaco_id' =>	134	),
            array('area_id' =>2, 'farmaco_id' =>	135	),
            array('area_id' =>2, 'farmaco_id' =>	136	),
            array('area_id' =>2, 'farmaco_id' =>	137	),
            array('area_id' =>2, 'farmaco_id' =>	138	),
            array('area_id' =>2, 'farmaco_id' =>	139	),
            array('area_id' =>2, 'farmaco_id' =>	140	),
            array('area_id' =>2, 'farmaco_id' =>	141	),
            array('area_id' =>2, 'farmaco_id' =>	142	),
            array('area_id' =>2, 'farmaco_id' =>	143	),
            array('area_id' =>2, 'farmaco_id' =>	144	),
            array('area_id' =>2, 'farmaco_id' =>	145	),
            array('area_id' =>2, 'farmaco_id' =>	146	),
            array('area_id' =>2, 'farmaco_id' =>	147	),
            array('area_id' =>2, 'farmaco_id' =>	148	),
            array('area_id' =>2, 'farmaco_id' =>	149	),
            array('area_id' =>2, 'farmaco_id' =>	150	),
            array('area_id' =>2, 'farmaco_id' =>	151	),
            array('area_id' =>2, 'farmaco_id' =>	152	),
            array('area_id' =>2, 'farmaco_id' =>	153	),
            array('area_id' =>2, 'farmaco_id' =>	154	),
            array('area_id' =>2, 'farmaco_id' =>	155	),
            array('area_id' =>2, 'farmaco_id' =>	156	),
            array('area_id' =>2, 'farmaco_id' =>	157	),
            array('area_id' =>2, 'farmaco_id' =>	158	),
            array('area_id' =>3, 'farmaco_id' =>	159	),
            array('area_id' =>3, 'farmaco_id' =>	160	),
            array('area_id' =>3, 'farmaco_id' =>	161	),
            array('area_id' =>3, 'farmaco_id' =>	162	),
            array('area_id' =>3, 'farmaco_id' =>	163	),
            array('area_id' =>3, 'farmaco_id' =>	164	),
            array('area_id' =>3, 'farmaco_id' =>	165	),
            array('area_id' =>3, 'farmaco_id' =>	166	),
            array('area_id' =>3, 'farmaco_id' =>	167	),
            array('area_id' =>3, 'farmaco_id' =>	168	),
            array('area_id' =>3, 'farmaco_id' =>	169	),
            array('area_id' =>3, 'farmaco_id' =>	170	),
            array('area_id' =>3, 'farmaco_id' =>	171	),
            array('area_id' =>3, 'farmaco_id' =>	172	),
            array('area_id' =>3, 'farmaco_id' =>	173	),
            array('area_id' =>3, 'farmaco_id' =>	174	),
            array('area_id' =>3, 'farmaco_id' =>	175	),
            array('area_id' =>3, 'farmaco_id' =>	176	),
                ];
                foreach ($farmacos as $farmaco) {
                    AreaFarmaco::create($farmaco);
                }
            }
    }
